#!/usr/bin/env bash

# Directions loosly taken from here: https://help.ubuntu.com/community/MakeALiveCD/DVD/BootableFlashFromHarddiskInstall

#exec 200>/var/lock/lrc-livecd
#flock -n 200 || exit 1

RELEASE=xenial

if ! test -d /var/chroot/$RELEASE ; then
	debootstrap $RELEASE /var/chroot/$RELEASE.part http://archive.ubuntu.com/ubuntu
	mv /var/chroot/$RELEASE.part /var/chroot/$RELEASE
fi

cat << EOF > /var/chroot/$RELEASE/finish-up.sh
#!/usr/bin/env bash

mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts

export HOME=/root
export LC_ALL=C

apt-get update
apt-get upgrade
apt-get install --yes \
	btrfs-tools \
	casper \
	dbus \
	discover \
	e2fsprogs \
	laptop-detect \
	linux-generic \
	lupin-casper \
	lvm2 \
	os-prober \
	reiser4progs \
	reiserfsprogs \
	squashfs-tools \
	ubuntu-standard \
	vim \
	xfsprogs

umount /proc
umount /sys
umount /dev/pts
EOF

chmod +x /var/chroot/$RELEASE/finish-up.sh

chroot /var/chroot/$RELEASE finish-up.sh
