#!/usr/bin/env bash

# /sys/class/block/sdd/device/{model,vendor}

devs=$(lsblk -d | sed 1d | awk '{print $1}')

for d in $devs ; do
	vendor=$(cat /sys/class/block/$d/device/vendor | awk '{print $1}')
	model=$(cat /sys/class/block/$d/device/model)
	removable=$(cat /sys/class/block/$d/removable)
	size=$(cat /sys/class/block/$d/size)
	size=$(( $size * 512 ))
	echo $d,$size,$removable,$vendor,$model
done

